
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klvywxjanicgbdxzcdgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsdnl3eGphbmljZ2JkeHpjZGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTM2MTYsImV4cCI6MjA2MTU2OTYxNn0.dSNo4jWoK-AfZiB1Lne5GeN_dMX-_csXwMvgy1izNS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  }
});
